# Generated by Django 5.0.7 on 2024-07-15 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='tilte',
        ),
    ]
