# Generated by Django 5.0.7 on 2024-07-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_comment_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='click_num',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
